=== Installing the plugin

Just proceed as with any other Grails 3 plugin:

[source,groovy,subs="attributes+"]
.`build.gradle`
----
dependencies {

    //Other dependencies

    compile "org.grails.plugins:spring-security-rest:{version}"

}
----

Once the plugin is installed, you are ready to go. The default configuration is to use signed
JWT's for tokens. However, you can select any other token storage strategy:

. Grails Cache.
. Memcached.
. GORM.
. Redis.
. Provide your own: implement
http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/gapi/grails/plugin/springsecurity/rest/token/storage/TokenStorageService.html[TokenStorageService]
and register it in `resources.groovy` as `tokenStorageService`.

=== Plugin configuration

This plugin is compatible by default with Spring Security core traditional, form-based authentication. The important thing
to remember is: you have to separate the filter chains, so different filters are applied on each case.

The stateless, token-based approach of this plugin is incompatible with the HTTP session-based approach of Spring Security,
core, so the trick is to identify what URL patterns have to be stateless, and what others have to be stateful (if any).

To configure the chains properly, you can use the `grails.plugin.springsecurity.filterChain.chainMap` property:

[source,groovy]
.Listing {counter:listing}. `grails.plugin.springsecurity.filterChain.chainMap`
----
grails.plugin.springsecurity.filterChain.chainMap = [
    //Stateless chain
    [
        pattern: '/api/**',
        filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
    ],

    //Traditional chain
    [
        pattern: '/**',
        filters: 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'
    ]
]
----

To understand this syntax, please read the
https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#filters[Spring Security Core documentation].
Long story short: `JOINED_FILTERS` refers to all the configured filters. The minus (`-`) notation means all the previous values
but the neglected one.

So the first chain applies all the filters except the stateful ones. The second one applies all the filters but the stateless ones.

[NOTE]
====
Make sure that the stateless chain applies not only to your REST controllers, but also to the URL's where this plugin
filters are listening: by default, `/api/login` for authentication, `/api/logout` for
logout and `/api/validate` for token validation.
====

The difference is that, in a traditional form-based authentication, Spring Security will respond with an HTTP 302 redirect
to the login controller. That doesn't work for an API, so in the stateless approach, an HTTP 401 response will be sent back.