=== JWT support

JWT is fully supported and is now the default token "storage" mechanism. If you still want to use your previous storage
(such as Memcached or GORM), make sure you explicitly set to `true` one of the following properties:

.New configuration values in 1.5
[cols="80,20"]
|===
|Config key |Default value

|`grails.plugin.springsecurity.rest.token.storage.useMemcached`
|`false`

|`grails.plugin.springsecurity.rest.token.storage.useGorm`
|`false`

|`grails.plugin.springsecurity.rest.token.storage.useGrailsCache`
|`false`
|===

If switching over JWT, the logout behavior is not available anymore. Read the documentation on how to
implement your own logout strategy if you want to.

=== Redis support

Redis can now be used as token storage service. Thanks to https://github.com/peh[Philipp Eschenbach] for
his initial contribution.

=== New package base

Packages `com.odobo.grails.plugin.springsecurity.rest.*` have been refactored to simply `grails.plugin.springsecurity.rest.*`.
Make sure to double-check your imports when upgrading to 1.5.

=== Other minor changes

* The plugin now uses Grails 2.4.4, and the build and tests are executed with Java 8.
* Documentation for older versions is now published at http://alvarosanchez.github.io/grails-spring-security-rest[]