name: Java CI
on:
  push:
    branches:
      - '[5-9].[0-9].x'
  pull_request:
    branches:
      - '[5-9].[0-9].x'
  workflow_dispatch:
jobs:
  core-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wrapper Integrity
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with: { java-version: 11, distribution: temurin }
      - name: Run Tests
        uses: gradle/actions/setup-gradle@v3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        with:
          arguments: |
            check 
            --refresh-dependencies
            -Dgeb.env=chromeHeadless
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wrapper Integrity
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Java
        uses: actions/setup-java@v4
        with: { java-version: 11, distribution: temurin }
      - name: Run Build
        id: build
        uses: gradle/actions/setup-gradle@v3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        with:
          arguments: |
            check 
            --refresh-dependencies
            -Dgeb.env=chromeHeadless